import '../models/city_config.dart';

class CityConfigService {
  static final List<CityConfig> defaultCities = [
    CityConfig(
      id: 'beijing',
      name: '北京',
      pensionBase: 5360,
      pensionBaseMax: 31884,
      pensionRate: 0.08,
      medicalRate: 0.02,
      unemploymentRate: 0.002,
      housingFundRate: 0.12,
      housingFundBase: 2200,
      housingFundBaseMax: 31884,
    ),
    CityConfig(
      id: 'shanghai',
      name: '上海',
      pensionBase: 7310,
      pensionBaseMax: 36549,
      pensionRate: 0.08,
      medicalRate: 0.02,
      unemploymentRate: 0.005,
      housingFundRate: 0.07,
      housingFundBase: 2590,
      housingFundBaseMax: 36549,
    ),
    CityConfig(
      id: 'guangzhou',
      name: '广州',
      pensionBase: 2300,
      pensionBaseMax: 36072,
      pensionRate: 0.08,
      medicalRate: 0.02,
      unemploymentRate: 0.002,
      housingFundRate: 0.05,
      housingFundBase: 2300,
      housingFundBaseMax: 36072,
    ),
    CityConfig(
      id: 'shenzhen',
      name: '深圳',
      pensionBase: 2360,
      pensionBaseMax: 36549,
      pensionRate: 0.08,
      medicalRate: 0.02,
      unemploymentRate: 0.003,
      housingFundRate: 0.05,
      housingFundBase: 2360,
      housingFundBaseMax: 36549,
    ),
    CityConfig(
      id: 'hangzhou',
      name: '杭州',
      pensionBase: 3957,
      pensionBaseMax: 19783,
      pensionRate: 0.08,
      medicalRate: 0.02,
      unemploymentRate: 0.005,
      housingFundRate: 0.12,
      housingFundBase: 2010,
      housingFundBaseMax: 36675,
    ),
    CityConfig(
      id: 'nanjing',
      name: '南京',
      pensionBase: 4494,
      pensionBaseMax: 24042,
      pensionRate: 0.08,
      medicalRate: 0.02,
      unemploymentRate: 0.005,
      housingFundRate: 0.12,
      housingFundBase: 2280,
      housingFundBaseMax: 34500,
    ),
    CityConfig(
      id: 'chengdu',
      name: '成都',
      pensionBase: 3726,
      pensionBaseMax: 18630,
      pensionRate: 0.08,
      medicalRate: 0.02,
      unemploymentRate: 0.004,
      housingFundRate: 0.12,
      housingFundBase: 1650,
      housingFundBaseMax: 22980,
    ),
    CityConfig(
      id: 'wuhan',
      name: '武汉',
      pensionBase: 4077,
      pensionBaseMax: 20385,
      pensionRate: 0.08,
      medicalRate: 0.02,
      unemploymentRate: 0.003,
      housingFundRate: 0.08,
      housingFundBase: 1750,
      housingFundBaseMax: 27730,
    ),
    CityConfig(
      id: 'xian',
      name: '西安',
      pensionBase: 3632,
      pensionBaseMax: 18159,
      pensionRate: 0.08,
      medicalRate: 0.02,
      unemploymentRate: 0.003,
      housingFundRate: 0.12,
      housingFundBase: 1680,
      housingFundBaseMax: 20955,
    ),
    CityConfig(
      id: 'chongqing',
      name: '重庆',
      pensionBase: 3699,
      pensionBaseMax: 18495,
      pensionRate: 0.08,
      medicalRate: 0.02,
      unemploymentRate: 0.005,
      housingFundRate: 0.12,
      housingFundBase: 1800,
      housingFundBaseMax: 24595,
    ),
  ];

  static CityConfig getCity(String id) {
    return defaultCities.firstWhere(
      (city) => city.id == id,
      orElse: () => defaultCities.first,
    );
  }

  static List<CityConfig> getAllCities() {
    return List.unmodifiable(defaultCities);
  }
}
